<?xml version="1.0" encoding="utf-8"?><Database Name="CloudCinemaDB" Class="CloudDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cloudcinema.database.windows.net;Initial Catalog=CloudCinemaDB;User ID=cloudcinema;Connect Timeout=60;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CloudCinemaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Schedule" Member="Schedule">
    <Type Name="Schedule">
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="movie_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="movie_date" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="movie_hour" Type="System.String" DbType="VarChar(5) NOT NULL" CanBeNull="false" />
      <Column Name="parking_zone" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
      <Column Name="capacity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="reserved_spots" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Schedule_Reservations" Member="Reservations" ThisKey="schedule_id" OtherKey="schedule_id" Type="Reservations" />
      <Association Name="Movies_Schedule" Member="Movies" ThisKey="movie_id" OtherKey="movie_id" Type="Movies" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUsers">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUsers_Reservations" Member="Reservations" ThisKey="Id" OtherKey="Id" Type="Reservations" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genre">
    <Type Name="Genre">
      <Column Name="genre_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Movies" Member="Movies" ThisKey="genre_id" OtherKey="genre_id" Type="Movies" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movies">
      <Column Name="movie_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="genre_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="trailer" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="price_per_spot" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movies_Schedule" Member="Schedule" ThisKey="movie_id" OtherKey="movie_id" Type="Schedule" />
      <Association Name="Genre_Movies" Member="Genre" ThisKey="genre_id" OtherKey="genre_id" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservations">
      <Column Name="reservation_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Schedule_Reservations" Member="Schedule" ThisKey="schedule_id" OtherKey="schedule_id" Type="Schedule" IsForeignKey="true" />
      <Association Name="AspNetUsers_Reservations" Member="AspNetUsers" ThisKey="Id" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
    </Type>
  </Table>
</Database>