<?xml version="1.0" encoding="utf-8"?><Database Name="CloudCinemaDB" Class="CloudBDDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=cloudcinema.database.windows.net;Initial Catalog=CloudCinemaDB;User ID=cloudcinema;Connect Timeout=60;Encrypt=True;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="CloudCinemaDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Showtimes" Member="Showtimes">
    <Type Name="Showtimes">
      <Column Name="showtime_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hour_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="screening_room_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Showtimes_Schedule" Member="Schedule" ThisKey="showtime_id" OtherKey="showtime_id" Type="Schedule" />
      <Association Name="Hours_Showtimes" Member="Hours" ThisKey="hour_id" OtherKey="hour_id" Type="Hours" IsForeignKey="true" />
      <Association Name="Screening_rooms_Showtimes" Member="Screening_rooms" ThisKey="screening_room_id" OtherKey="screening_room_id" Type="Screening_rooms" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AspNetUsers" Member="AspNetUsers">
    <Type Name="AspNetUsers">
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SecurityStamp" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Association Name="AspNetUsers_Reservations" Member="Reservations" ThisKey="Id" OtherKey="Id" Type="Reservations" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genre">
    <Type Name="Genre">
      <Column Name="genre_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Movies" Member="Movies" ThisKey="genre_id" OtherKey="genre_id" Type="Movies" />
    </Type>
  </Table>
  <Table Name="dbo.Hours" Member="Hours">
    <Type Name="Hours">
      <Column Name="hour_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="hour_name" Type="System.String" DbType="NVarChar(10) NOT NULL" CanBeNull="false" />
      <Association Name="Hours_Showtimes" Member="Showtimes" ThisKey="hour_id" OtherKey="hour_id" Type="Showtimes" />
    </Type>
  </Table>
  <Table Name="dbo.Movies" Member="Movies">
    <Type Name="Movies">
      <Column Name="movie_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="genre_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="title" Type="System.String" DbType="NVarChar(120) NOT NULL" CanBeNull="false" />
      <Column Name="trailer" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="price_per_seat" Type="System.Decimal" DbType="Decimal(18,0) NOT NULL" CanBeNull="false" />
      <Column Name="description" Type="System.String" DbType="NVarChar(4000)" CanBeNull="true" />
      <Column Name="duration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movies_Schedule" Member="Schedule" ThisKey="movie_id" OtherKey="movie_id" Type="Schedule" />
      <Association Name="Genre_Movies" Member="Genre" ThisKey="genre_id" OtherKey="genre_id" Type="Genre" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Reservations" Member="Reservations">
    <Type Name="Reservations">
      <Column Name="reservation_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Association Name="Reservations_Seats" Member="Seats" ThisKey="reservation_id" OtherKey="reservation_id" Type="Seats" />
      <Association Name="AspNetUsers_Reservations" Member="AspNetUsers" ThisKey="Id" OtherKey="Id" Type="AspNetUsers" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Schedule" Member="Schedule">
    <Type Name="Schedule">
      <Column Name="schedule_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="showtime_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="movie_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="seat_id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="movie_date" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Movies_Schedule" Member="Movies" ThisKey="movie_id" OtherKey="movie_id" Type="Movies" IsForeignKey="true" />
      <Association Name="Showtimes_Schedule" Member="Showtimes" ThisKey="showtime_id" OtherKey="showtime_id" Type="Showtimes" IsForeignKey="true" />
      <Association Name="Seats_Schedule" Member="Seats" ThisKey="seat_id" OtherKey="seat_id" Type="Seats" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Screening_rooms" Member="Screening_rooms">
    <Type Name="Screening_rooms">
      <Column Name="screening_room_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Association Name="Screening_rooms_Showtimes" Member="Showtimes" ThisKey="screening_room_id" OtherKey="screening_room_id" Type="Showtimes" />
    </Type>
  </Table>
  <Table Name="dbo.Seats" Member="Seats">
    <Type Name="Seats">
      <Column Name="seat_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="reservation_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="seat_column" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="seat_row" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Seats_Schedule" Member="Schedule" ThisKey="seat_id" OtherKey="seat_id" Type="Schedule" />
      <Association Name="Reservations_Seats" Member="Reservations" ThisKey="reservation_id" OtherKey="reservation_id" Type="Reservations" IsForeignKey="true" />
    </Type>
  </Table>
</Database>